# Generated by Django 6.0 on 2026-01-23 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票名称')),
                ('exchange', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易所')),
                ('asset_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='资产类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票基础信息',
                'verbose_name_plural': '股票基础信息',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='板块')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='细分行业')),
                ('market_cap', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='市值')),
                ('pe_ratio', models.FloatField(blank=True, null=True, verbose_name='市盈率(TTM)')),
                ('forward_pe', models.FloatField(blank=True, null=True, verbose_name='预测市盈率')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='员工数')),
                ('website', models.URLField(blank=True, null=True, verbose_name='公司官网')),
                ('description', models.TextField(blank=True, null=True, verbose_name='公司简介')),
                ('raw_info', models.JSONField(blank=True, null=True, verbose_name='原始Info数据')),
                ('financial_data', models.JSONField(blank=True, null=True, verbose_name='结构化财务数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='上次更新时间')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='stock.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票基本面',
                'verbose_name_plural': '股票基本面',
            },
        ),
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='当前价格')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='涨跌额')),
                ('change_pct', models.FloatField(blank=True, null=True, verbose_name='涨跌幅(%)')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('prev_close', models.FloatField(blank=True, null=True, verbose_name='昨收')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='开盘')),
                ('day_high', models.FloatField(blank=True, null=True, verbose_name='最高')),
                ('day_low', models.FloatField(blank=True, null=True, verbose_name='最低')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='行情时间')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='stock.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票实时行情',
                'verbose_name_plural': '股票实时行情',
            },
        ),
        migrations.CreateModel(
            name='StockKLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='时间')),
                ('period', models.CharField(db_index=True, default='1d', max_length=10, verbose_name='周期')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='stock.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票K线',
                'verbose_name_plural': '股票K线',
                'indexes': [models.Index(fields=['stock', 'period', 'date'], name='stock_stock_stock_i_4cc006_idx')],
                'unique_together': {('stock', 'date', 'period')},
            },
        ),
    ]
