# Generated by Django 6.0 on 2025-12-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('duration', models.CharField(default='5y', max_length=20)),
                ('bar_size', models.CharField(default='1 day', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('task_result_id', models.CharField(blank=True, max_length=128, null=True)),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('signals', models.JSONField(blank=True, null=True)),
                ('candles', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('ai_prompt', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('symbol', 'duration', 'bar_size')},
            },
        ),
    ]
