# Generated by Django 6.0 on 2026-01-22 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='会话摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='股票名称')),
                ('exchange', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易所')),
                ('asset_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='资产类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票基础信息',
                'verbose_name_plural': '股票基础信息',
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ystock.chatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('duration', models.CharField(default='5y', max_length=20)),
                ('bar_size', models.CharField(default='1 day', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('task_result_id', models.CharField(blank=True, max_length=128, null=True)),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('signals', models.JSONField(blank=True, null=True)),
                ('candles', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('symbol', 'duration', 'bar_size')},
            },
        ),
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='板块')),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='细分行业')),
                ('market_cap', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='市值')),
                ('pe_ratio', models.FloatField(blank=True, null=True, verbose_name='市盈率(TTM)')),
                ('forward_pe', models.FloatField(blank=True, null=True, verbose_name='预测市盈率')),
                ('employees', models.IntegerField(blank=True, null=True, verbose_name='员工数')),
                ('website', models.URLField(blank=True, null=True, verbose_name='公司官网')),
                ('description', models.TextField(blank=True, null=True, verbose_name='公司简介')),
                ('raw_info', models.JSONField(blank=True, null=True, verbose_name='原始Info数据')),
                ('financial_data', models.JSONField(blank=True, null=True, verbose_name='结构化财务数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='上次更新时间')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ystock.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票基本面',
                'verbose_name_plural': '股票基本面',
            },
        ),
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='当前价格')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='涨跌额')),
                ('change_pct', models.FloatField(blank=True, null=True, verbose_name='涨跌幅(%)')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='成交量')),
                ('prev_close', models.FloatField(blank=True, null=True, verbose_name='昨收')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='开盘')),
                ('day_high', models.FloatField(blank=True, null=True, verbose_name='最高')),
                ('day_low', models.FloatField(blank=True, null=True, verbose_name='最低')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='行情时间')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='ystock.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票实时行情',
                'verbose_name_plural': '股票实时行情',
            },
        ),
        migrations.CreateModel(
            name='StockKLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('period', models.CharField(db_index=True, default='1d', max_length=10, verbose_name='周期')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('adj_close', models.FloatField(blank=True, null=True, verbose_name='复权收盘价')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='ystock.stock', verbose_name='股票')),
            ],
            options={
                'verbose_name': '股票历史K线',
                'verbose_name_plural': '股票历史K线',
                'ordering': ('date',),
                'unique_together': {('stock', 'date', 'period')},
            },
        ),
    ]
