# Generated by Django 6.0 on 2026-01-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('symbol',),
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='会话摘要')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称')),
                ('context_symbols', models.JSONField(blank=True, default=list, verbose_name='会话关注的股票代码列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI聊天会话',
                'verbose_name_plural': 'AI聊天会话',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='ystock_chat_updated_fc09e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('duration', models.CharField(default='5y', max_length=20)),
                ('bar_size', models.CharField(default='1 day', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('task_result_id', models.CharField(blank=True, max_length=128, null=True)),
                ('indicators', models.JSONField(blank=True, null=True)),
                ('signals', models.JSONField(blank=True, null=True)),
                ('candles', models.JSONField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('ai_prompt', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
                'unique_together': {('symbol', 'duration', 'bar_size')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('streaming', '生成中'), ('completed', '已完成'), ('error', '错误'), ('cancelled', '已取消')], default='completed', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('feedback', models.IntegerField(default=0, verbose_name='反馈')),
                ('thoughts', models.JSONField(blank=True, default=list, verbose_name='思考过程')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据（如引用的股票代码、指标数据等）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ystock.chatmessage', verbose_name='父消息')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ystock.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI聊天消息',
                'verbose_name_plural': 'AI聊天消息',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='ystock_chat_session_64ef42_idx'), models.Index(fields=['session', 'status'], name='ystock_chat_session_75f32d_idx')],
            },
        ),
    ]
