# Generated by Django 6.0 on 2026-01-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称'),
        ),
    ]
