# Generated by Django 6.0 on 2026-01-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockkline',
            options={'verbose_name': '股票K线', 'verbose_name_plural': '股票K线'},
        ),
        migrations.RemoveField(
            model_name='stockkline',
            name='adj_close',
        ),
        migrations.AlterField(
            model_name='stockkline',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='时间'),
        ),
        migrations.AddIndex(
            model_name='stockkline',
            index=models.Index(fields=['stock', 'period', 'date'], name='ystock_stoc_stock_i_9a6e97_idx'),
        ),
    ]
