# Generated by Django 6.0 on 2026-01-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0002_chatsession_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='thoughts',
            field=models.JSONField(blank=True, default=list, verbose_name='思考过程'),
        ),
    ]
