# Generated by Django 6.0 on 2026-01-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0002_alter_stockkline_options_remove_stockkline_adj_close_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockAnalysis',
        ),
    ]
