# Generated by Django 6.0 on 2026-01-13 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ystock_chat_session_64ef42_idx',
            old_name='ystock_chat_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='ystock_chat_session_75f32d_idx',
            old_name='ystock_chat_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='ystock_chat_updated_fc09e3_idx',
            old_name='ystock_chat_updated_idx',
        ),
    ]
