# Generated by Django 6.0 on 2026-01-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0003_delete_stockanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='元数据'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thoughts',
            field=models.JSONField(blank=True, null=True, verbose_name='思维链'),
        ),
    ]
