# Generated by Django 6.0 on 2026-01-13 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ystock', '0003_rename_ystock_chat_session_created_idx_ystock_chat_session_64ef42_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.IntegerField(default=0, verbose_name='反馈'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ystock.chatmessage', verbose_name='父消息'),
        ),
    ]
