# Generated by Django 6.0 on 2026-01-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_chatsession_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='会话标题'),
        ),
    ]
